### ISSUE TITLE
How to have more control on calibrant lists

### ISSUE THREAD

**Issue by denis-abusammour** [LaRoccaRaphael/MSI_recalibration#1]
I have a question regarding fetched calibrant lists. As far as I understood, calibrants are fetched from datasets, which in turn are filtered based on on available `metadata.columns`. I would like to exert more control over the fetched calibrants: 

- limit the number of datasets used for extracting the calibrants. 
- extract calibrants detected with a specific FDR, for example, to fetch all calibrants that were verified at <20% FDR. 
- extract calibrants that were identified against a specific database, say HMDB or SwissLipids. 

Please advise. Thanks.

**Comment by LaRoccaRaphael** [comment]
Hi,

The functions in the file recalibration/internal_calibrants_generation.ipynd have been modified to:
- use a given number of datasets
- limit the annotations according to their FDR
- limit the annotations from a particular database
- select datasets according to their number of annotations

Examples of how to use the new functions have been added.
